### PR TITLE
Improve syntax highlighting in code samples a bit!

### PR DESCRIPTION
**Pull request by thennothinghappened**
I was having a look at the manual and again noticed how bare-bones the syntax highlighting is, how it is missing keywords such as `new` and `static`, how it doesn't highlight variable colours, struct members... and so on. I decided today to take it upon myself to have a go learning some of [highlight.js](https://highlightjs.readthedocs.io)'s s way of defining language highlighers and use that to improve the manual's highlighting, as it uses this library for it.

**The changes are as follows, with before and after images!**

1. `new` keyword is highlighted:

**Before:**
image

**After:**
image

2. `#macro`, `#region`, `#endregion` are highlighted, including comment highlighting for the latter two, and constant colouring for the identifier for macros:

**Before:**
image
image

**After:**
image
image

3. Multi-line strings:

**Before:**
image

...note that it didn't even pick up GML as the language here as it didn't see it as valid syntax.

**After:**
image

4. Variable declarations, and struct literal members:

**Before:**
image
image

**After:**
image
image

5. Function declarations and call sites (for user functions):

**Before:**
image

**After:**
image

6. `throw` keyword is highlighted:

**Before:**
image

**After:**
image

7. Property accesses highlighted, with special colouration for `global`:

**Before:**
image
image

**After:**
image
image

8. Sneaky highlighting for `obj_*`, `spr_*` and `shader_*` as asset constant colours:

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by thennothinghappened** [comment]
I've also just added `try`, `catch` and `finally` which were missing. Another thing I'd like to point out is that since functions are now detected by call signature, that means anything that looks like `this(/*...*/)` will be highlighted, also applying to built-in functions of course.

There's a massive master list of every function in the engine in the `gml.js` file, which I can't tell if it is used for any other purpose than to manually highlight them. If that's the only reason it exists, this can now be safely removed, to the death of much manual data-entry!

**Comment by thennothinghappened** [comment]
Added support for enums!

image
image

I've also gone and added some documentation for the various modes I've added, as they're not too self-explanatory at first glance.

Finally, I added some negative look-behind and look-ahead assertions to the `VALID_IDENTIFIER_REG` regex, because it was getting false-positives on `<br />`, and was matching the `br` in there as a variable which isn't correct obviously. I might have a look at a better way of handling this as I'm not too comfortable with it working that way, since these assertions to my knowledge are only supported in the latest browser versions, which might break the manual(!) for people on outdated browsers. This false positive issue has come up a few times and I'd worked around it, but it was a big issue for enum entries so I added those assertions in.

I'm going to have a look if I can do some sort of pre-processing on the input to steal all the `<br />` instances and replace them with proper line breaks, but really the solution to this would be if the manual switched its code sample blocks to use `white-space: pre-wrap`, ditched all the non-breaking spaces and formatted code samples more properly in the HTML. My understanding however is that RoboHelp is some sort of WYSIWYG editor(?) which makes this not really an option as it would be responsible for the incorrect formatting.

If I can't find a good solution, and it seems apparent that the assertions are not widely supported enough, then I'll remove them and turn off the `enum` entry colouring, alongside any additional more complex state-based colouring I'd otherwise like to add.

**Comment by thennothinghappened** [comment]
Alrighty, I'm back again!

I've made a slight modification to the `highlight.js` script - which by the looks of things someone had already made a similar, though slightly different modification at some point earlier - and made sure that the language definition regex only gets passed `\n` instead of `<br>`. This was pretty easy to do and means that nasty lookbehind assertion is gone, and the whole thing is a lot simpler and more stable.

**Comment by thennothinghappened** [comment]
Added support for GML's underscores in number literals, and `$` and `#` colour hex!
image
image
image
image

**Comment by gnysek** [comment]
I made few pull requests for highlight.js from time to time, updating GML ( https://github.com/highlightjs/highlight.js/pulls?q=is%3Apr+author%3Agnysek+is%3Aclosed ), but with it rapid updates it's for sure out of date again. Latest version I've updated was 2024.2 - so if you have any newer definitions file, would be nice to update it in hightlight.js repo too! :)

**Comment by thennothinghappened** [comment]
> I made few pull requests for highlight.js from time to time, updating GML ( https://github.com/highlightjs/highlight.js/pulls?q=is%3Apr+author%3Agnysek+is%3Aclosed ), but with it rapid updates it's for sure out of date again. Latest version I've updated was 2024.2 - so if you have any newer definitions file, would be nice to update it in hightlight.js repo too! :)

Heya! I thought about porting it across but I'm unfamiliar with contributing to that project - I've made substantial changes to how the language definition for GML works and might have a few more edge cases to sort out I've not found. I'm now quite sure the manual list of function names in there is made unnecessary by my changes so will go ahead with removing it.

If/when this PR is accepted, I'll happily open one in highlight.js itself to backport my changes, which should make the highlighting in Discord etc. much better  (eventually!) :)

**Comment by thennothinghappened** [comment]
Just gone ahead with removing that massive function list as I'm now quite certain it was only used for manually highlighting function calls. Since that's now done by signature, I've removed that list and it won't need manual updating anymore :)

**Comment by gurpreetsinghmatharoo** [comment]
Merged. Thank you so much for your work!

**Pull request merged**
